# Generated by Django 4.1.6 on 2023-02-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='from_start',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
