# Generated by Django 4.1.6 on 2023-02-07 08:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("animal_api", "0002_user_from_start_user_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="latitude"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="longiude"
                    ),
                ),
                (
                    "point",
                    models.JSONField(
                        unique=True,
                        verbose_name=(
                            models.DecimalField(
                                decimal_places=6, max_digits=9, verbose_name="latitude"
                            ),
                            models.DecimalField(
                                decimal_places=6, max_digits=9, verbose_name="longiude"
                            ),
                        ),
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="firstName",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="from_start",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="count from start"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="lastName",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="last name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=100, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="user",
            name="size",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="size"
            ),
        ),
    ]
