# Generated by Django 4.1.6 on 2023-02-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animal_api", "0003_location_alter_user_email_alter_user_firstname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="point",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                unique=True,
                verbose_name="Point(latitude, longiude)",
            ),
        ),
    ]
