# Generated by Django 4.1.6 on 2023-02-07 10:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("animal_api", "0004_alter_location_point"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weight",
                    models.FloatField(blank=True, null=True, verbose_name="weight"),
                ),
                (
                    "length",
                    models.FloatField(blank=True, null=True, verbose_name="length"),
                ),
                (
                    "height",
                    models.FloatField(blank=True, null=True, verbose_name="height"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "MALE"),
                            ("FEMALE", "FEMALE"),
                            ("OTHER", "OTHER"),
                        ],
                        default="OTHER",
                        max_length=50,
                        null=True,
                        verbose_name="gender",
                    ),
                ),
                (
                    "life_status",
                    models.CharField(
                        blank=True,
                        choices=[("ALIVE", "ALIVE"), ("DEAD", "DEAD")],
                        default="ALIVE",
                        max_length=50,
                        null=True,
                        verbose_name="life_status",
                    ),
                ),
                ("chipping_date_time", models.DateTimeField(auto_now=True)),
                (
                    "chipper_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "chipping_location_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "death_date_time",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="death_date_time",
                    ),
                ),
            ],
            options={
                "verbose_name": "Животное",
                "verbose_name_plural": "Животные",
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name": "Локация", "verbose_name_plural": "Локации"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="VisitedLocations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "animal",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="animal_api.animal",
                    ),
                ),
                (
                    "visited_location",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="animal_api.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Посещенная локация",
                "verbose_name_plural": "Посещенные локации",
            },
        ),
        migrations.CreateModel(
            name="AnimalTypes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "animal_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="animal_api.animal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип животного",
                "verbose_name_plural": "Типы животного",
            },
        ),
    ]
