# Generated by Django 4.1.6 on 2023-02-07 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("animal_api", "0006_alter_animal_chipping_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="animaltypes",
            name="animal",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="animal_api.animal",
            ),
        ),
        migrations.AlterField(
            model_name="animaltypes",
            name="animal_type",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                unique=True,
                verbose_name="animal_type",
            ),
        ),
    ]
